version: '3'

services:
  bamboo:
    image: atlassian/bamboo-server:7.1.4
    volumes:
      - /data/bamboo-home:/var/atlassian/bamboo
    ports:
      - '8085:8085'
      - '54663:54663'
    env_file:
      - bamboo.env
  postgresql:
    image: postgres:9.6
    container_name: postgres
    hostname: postgres
    volumes:
      - /data/postgresql-data:/var/lib/postgresql/data
    env_file:
      - postgres.env
networks:
  default:
    external:
      name: devopsbridge
