version: '3'

services:
  jira:
    depends_on:
      - postgresql
    image: atlassian/jira-software:8.13.0-ubuntu
    volumes:
      - /data/jira-data:/var/atlassian/jira
    ports:
      - 8080:8080
    environment:
      - JVM_MINIMUM_MEMORY:384m
      - JVM_MAXIMUM_MEMORY:768m
      - JVM_RESERVED_CODE_CACHE_SIZE:512m
      # Reverse Proxy Settings
      #- ATL_PROXY_NAME
      #- ATL_PROXY_PORT
      #- ATL_TOMCAT_PORT
      #- ATL_TOMCAT_SCHEME

  postgresql:
    image: postgres:9.6
    volumes:
      - /data/postgres-data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jira'
      - 'POSTGRES_PASSWORD=jellyfish'
      - 'POSTGRES_ENCODING=UNICODE' # https://confluence.atlassian.com/adminjiraserver/connecting-jira-applications-to-postgresql-938846851.html
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'

networks:
  default:
    external:
      name: devopsbridge