version: "3.9"

services:
  postgres:
    image: "postgres:9.6"
    restart: unless-stopped
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  pgadmin:
    image: "dpage/pgadmin4:4"
    restart: unless-stopped
    env_file:
      - pg.env
    ports:
      - 8080:80
    depends_on:
      - postgres
    volumes: 
      - pgadmin-data:/var/lib/pgadmin
    
volumes:
  postgres-data:
  pgadmin-data:
  
# https://www.pgadmin.org/docs/pgadmin4/development/container_deployment.html
