version: "3"

services:
  postgres:
    image: "postgres:9.6"
    restart: unless-stopped
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    networks: 
      - front
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  pgadmin:
    image: "dpage/pgadmin4:4"
    restart: unless-stopped
    env_file:
      - pg.env
    ports:
      - 8080:80
    depends_on:
      - postgres
    networks: 
      - front
    volumes: 
      - pgadmin-data:/var/lib/pgadmin

networks:
    front:
      driver: bridge
#      driver_opts:
#        com.docker.network.enable_ipv6: "true"
      ipam:
        driver: default
        config:
          - subnet: 192.168.0.2/24
#            gateway: 192.168.0.1

    
volumes:
  postgres-data:
  pgadmin-data:
  
# https://www.pgadmin.org/docs/pgadmin4/development/container_deployment.html
