version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.10.1
    volumes:
      - type: bind
        source: /data/elastic-data
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTICSEARCH_USERNAME: elastic
      ELASTIC_PASSWORD: ssw0rd1
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node


  logstash:
    image: logstash:7.10.1
    restart: unless-stopped
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    # volumes:
    #   - /date/logstash-data/pipeline:/usr/share/logstash/pipeline


  kibana:
    image: kibana:7.10.1
    restart: unless-stopped
    environment: 
      ELASTICSEARCH_PASSWORD: P@ssw0rd1
      ELASTICSEARCH_URL: http://192.168.0.20:9200
      ELASTICSEARCH_USERNAME: elastic
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    volumes:
      - /data/kibana-data/kibana.yml:/usr/share/kibana/config/kibana.yml

networks:
  default:
    external:
      name: devopsbridge