version: "3"

services:
  sonarqube:
    image: sonarqube:8.6.0-community
    depends_on:
      - db
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      # https://docs.sonarqube.org/latest/setup/environment-variables/

    volumes:
      - /data/sonarqube/sonarqube_data:/opt/sonarqube/data
      - /data/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - /data/sonarqube/sonarqube_logs:/opt/sonarqube/logs
      - /data/sonarqube/sonarqube_temp:/opt/sonarqube/temp
      # sonarqube_data – contains data files, such as the embedded H2 database and Elasticsearch indexes
      # sonarqube_logs – contains SonarQube logs about access, web process, CE process, and Elasticsearch
      # sonarqube_extensions – will contain any plugins you install and the Oracle JDBC driver if necessary.

  db:
    image: postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - /data/postgresql-data:/var/lib/postgresql/data

networks:
  default:
    external:
      name: devopsbridge
